title: Competitive Programming Journal
author: DVD_OSO
email: davidjiang0307@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Competitive Programming Journal
# social links
#twitter_username: Stuff # DO NOT include the @ character, or else the build will fail!
github_username:  DVDOSO # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
